### 配置 JDBC 连接信息
spring:
   datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url:
     username: root
     password: root
     ### 设定所使用的数据库连接池为 Druid
     type: com.alibaba.druid.pool.DruidDataSource
     ### 配置druid 信息
     druid:
       min-idle: 3
       max-active: 15
       initial-size: 5
       min-evictable-idle-time-millis: 30000
       max-evictable-idle-time-millis: 60000
### 配置mybtis 项目信息
mybatis:
  mapper-locations: classpath:/mapper/*/*/*.Mapper.xml
  type-aliases-package: com.zhang.mims